// Netlify Function: /api/send-email
// Sends PDF report via email using Resend

const fetch = require('node-fetch');

exports.handler = async (event, context) => {
    // Only allow POST
    if (event.httpMethod !== 'POST') {
        return {
            statusCode: 405,
            body: JSON.stringify({ error: 'Method not allowed' })
        };
    }

    try {
        const data = JSON.parse(event.body);

        // Validate required fields
        if (!data.email || !data.pdfBase64) {
            return {
                statusCode: 400,
                body: JSON.stringify({ error: 'Missing required data' })
            };
        }

        const RESEND_API_KEY = process.env.RESEND_API_KEY;

        if (!RESEND_API_KEY) {
            console.error('Resend API key not configured');
            return {
                statusCode: 500,
                body: JSON.stringify({ error: 'Email service not configured' })
            };
        }

        const companyName = data.companyName || 'Your Company';
        const period = data.period || 'Report';
        const filename = `${companyName.replace(/\s+/g, '_')}_${period.replace(/\s+/g, '_')}.pdf`;

        // Send email via Resend
        const response = await fetch('https://api.resend.com/emails', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${RESEND_API_KEY}`
            },
            body: JSON.stringify({
                from: 'PlainFinance <reports@plainfinance.co>',
                to: [data.email],
                subject: `Your Financial Report: ${companyName} - ${period}`,
                html: `
                    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
                        <h2 style="color: #1e3a5f;">Your PlainFinance Report is Ready</h2>
                        <p>Hi,</p>
                        <p>Please find attached your financial report for <strong>${companyName}</strong> (${period}).</p>
                        <p>This report includes:</p>
                        <ul>
                            <li>Profit and loss summary</li>
                            <li>5 key business health metrics</li>
                            <li>Cash flow analysis</li>
                            <li>3 recommended actions</li>
                            <li>Summary for bank meetings</li>
                        </ul>
                        <p>If you have any questions about your report, reply to this email.</p>
                        <hr style="border: none; border-top: 1px solid #e2e8f0; margin: 24px 0;">
                        <p style="color: #64748b; font-size: 14px;">
                            Generated by <strong>PlainFinance</strong><br>
                            Finance for Non-Finance People
                        </p>
                    </div>
                `,
                attachments: [
                    {
                        filename: filename,
                        content: data.pdfBase64
                    }
                ]
            })
        });

        const result = await response.json();

        if (response.ok) {
            return {
                statusCode: 200,
                headers: {
                    'Content-Type': 'application/json',
                    'Access-Control-Allow-Origin': '*'
                },
                body: JSON.stringify({
                    success: true,
                    message: 'Email sent successfully'
                })
            };
        } else {
            console.error('Resend API error:', result);
            return {
                statusCode: 500,
                body: JSON.stringify({ error: result.message || 'Failed to send email' })
            };
        }

    } catch (error) {
        console.error('Error:', error);
        return {
            statusCode: 500,
            body: JSON.stringify({ error: 'Failed to send email. Please try again.' })
        };
    }
};
